# GitHub Pages Configuration for Udita Ranade Website

# Site settings
title: "Udita Ranade - Professional Singer & Performer"
description: "Professional Singer & Performer captivating audiences worldwide with powerful vocals and emotive performances across multiple genres and languages."
url: "https://nir351988.github.io"
baseurl: "/UditaRanadeWebsite"

# Author information
author:
  name: "Udita Ranade"
  email: "contact@uditaranade.com"
  bio: "Professional Singer & Performer | Multi-Genre Vocalist | Recording Artist"
  
# Musical specializations
music:
  primary_style: "Contemporary Classical"
  secondary_styles: ["Opera", "World Music", "Jazz Standards"]
  specialties: ["Solo Performances", "Ensemble Work", "Recording", "Voice Coaching"]
  languages: ["English", "Italian", "French", "German", "Spanish"]
  venues: ["Concert Halls", "Opera Houses", "Recording Studios", "Private Events"]

# SEO settings
twitter:
  username: "uditaranade"
  card: "summary_large_image"

facebook:
  app_id: ""
  publisher: ""

og_image: "/assets/images/udita-hero.jpg"

# Social media profiles
social:
  - name: "Facebook"
    url: "https://facebook.com/uditaranade"
    icon: "fab fa-facebook"
  - name: "Instagram"
    url: "https://instagram.com/uditaranade"
    icon: "fab fa-instagram"
  - name: "YouTube"
    url: "https://youtube.com/@uditaranade"
    icon: "fab fa-youtube"
  - name: "Spotify"
    url: "https://open.spotify.com/artist/uditaranade"
    icon: "fab fa-spotify"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Include/Exclude files
include:
  - _pages
  - assets
  - .htaccess

exclude:
  - README.md
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - gemfiles
  - Gemfile
  - Gemfile.lock

# Collections
collections:
  concerts:
    output: true
    permalink: /:collection/:name/
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/
  ragas:
    output: true
    permalink: /ragas/:name/
  performances:
    output: true
    permalink: /performances/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "concerts"
    values:
      layout: "concert"
  - scope:
      path: ""
      type: "news"
    values:
      layout: "post"

# Plugin settings
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# SEO and Analytics
google_analytics: ""
google_site_verification: ""

# Performance settings
sass:
  style: compressed

# Security settings
webrick:
  headers:
    "X-Frame-Options": "SAMEORIGIN"
    "X-Content-Type-Options": "nosniff"
    "X-XSS-Protection": "1; mode=block"
    "Strict-Transport-Security": "max-age=31536000; includeSubDomains"